# Generated by Django 4.2.10 on 2024-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_concert', models.CharField(max_length=12, verbose_name='Дата концерта')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0)),
                ('cost', models.CharField(default='', max_length=12, verbose_name='Цена')),
            ],
            options={
                'ordering': ['date_concert'],
                'indexes': [models.Index(fields=['date_concert'], name='homepage_co_date_co_c32f24_idx')],
            },
        ),
    ]
