# Generated by Django 4.2.10 on 2024-04-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_musicians'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.CharField(max_length=2550, verbose_name='Текст')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['time'], name='homepage_hi_time_bc63db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='homepage.history')),
            ],
        ),
    ]
