# Generated by Django 4.2.10 on 2024-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_history_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerts',
            name='date_concert',
            field=models.DateTimeField(),
        ),
    ]
