# Generated by Django 4.2.10 on 2024-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_concerts_date_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
