# Generated by Django 4.2.10 on 2024-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_foto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerts',
            name='url_ticket',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на покупку билетов'),
        ),
    ]
