# Generated by Django 4.2.10 on 2024-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_concerts_url_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.CharField(max_length=2550, verbose_name='Текст')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(max_length=2550, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='text',
            field=models.TextField(max_length=2550, verbose_name='Текст'),
        ),
    ]
