# Generated by Django 4.2.10 on 2024-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_merch_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='text',
            field=models.TextField(max_length=2550, verbose_name='Текст'),
        ),
    ]
