# Generated by Django 4.2.10 on 2024-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_merch_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(null=True, verbose_name='ID товара')),
                ('quantity', models.IntegerField(null=True, verbose_name='Количество')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес пункта выдачи СДЕК')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('pay', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
