# Generated by Django 4.2.10 on 2024-05-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='homepage.merch'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, verbose_name='Размер'),
        ),
    ]
