# Generated by Django 4.2.10 on 2024-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_purchase_item_alter_purchase_data_alter_purchase_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id_product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='name_product',
            field=models.IntegerField(null=True, verbose_name='Название товара'),
        ),
    ]
