# Generated by Django 4.2.10 on 2024-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_purchase_id_product_purchase_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name_product',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
    ]
